### ISSUE TITLE
Allow shellfoundry to uninstall a shell

### ISSUE THREAD

**Issue by kalsky** [QualiSystems/shellfoundry#58]
### Issue details

If you rename a shell, you'll end up with 2 shell templates (when creating a resource in the inventory).
The only way to delete a shell resource template is from the api (DeleteResourceTemplate).
Would be nice if the shellfoundry will be able to uninstall at least the shell resource template, and in the future maybe also the whole shell (attirbutes, model, etc).
### Steps to reproduce

install a shell
rename it in the shellconfig.xml
install the shell again
you now have 2 templates using the same model and driver.

you now need to use the api to remove the old shell template like this:

import cloudshell.api.cloudshell_api

csapi = cloudshell.api.cloudshell_api.CloudShellAPISession("localhost", "user", "password", "domain")
csapi.DeleteResourceTemplate("old shell name")

**Comment by borismod** [comment]
@kalsky thank you for reporting this. ShellFoundry uses Package Import for installing shells. It behaves the same way like importing a Quali Package via the portal. As you know, once package is imported, it cannot be "uninstalled" it. Since this is a common issue, it will be addressed in CloudShell 7.2 via Shell Entity feature, which will allow uninstalling shells.

**Comment by doppleware** [comment]
@kalsky for now the flow is to use our SDK edition and reset the database when you need to reset the sate

**Comment by kalsky** [comment]
Maybe we can now add support for this for the 2nd gen shells

**Comment by Costya-Y** [comment]
Waiting for api methods to be implemented in CloudShell
